### ISSUE TITLE
Visualizing BioPaxModels in Python?

### ISSUE THREAD

**Issue by dhimmel** [indralab/pybiopax#28]
I was curious whether there's any ways to visualize a pathway network after loading it as a `pybiopax.biopax.model.BioPaxModel`? Not sure if visualization is in scope for this package, but a visualization example notebook might mike the models more approachable.

_interested as part of https://github.com/openjournals/joss-reviews/issues/4136_

**Comment by bgyori** [comment]
That's a great question! I have an initial implementation of a networkx representation for objects (nodes) and references (edges) between them. However, this visualizes the raw OWL structure of the model which is not necessarily useful for seeing the actual reactions with their inputs and outputs. For that, https://github.com/PathwayCommons/chibe is a great tool that allows loading a BioPAX OWL file for visualization.
