### ISSUE TITLE
State of the field section in JOSS paper

### ISSUE THREAD

**Issue by leonweber** [indralab/pybiopax#30]
The state of the field section seems to be missing from `paper/paper.md`. In this related work such as [this](https://academic.oup.com/bioinformatics/article/36/15/4377/5841664) should be discussed.

**Comment by bgyori** [comment]
Hello @leonweber, thank you for the feedback! We are not aware of a requirement to have a separate state of field section in JOSS papers (see https://joss.readthedocs.io/en/latest/submitting.html). We mention several related tools in the Statement of Need section and will include additional ones including the one you posted in an update.
