### ISSUE TITLE
Converting BioPAX to signed directed pairwise graph

### ISSUE THREAD

**Issue by agitter** [indralab/pybiopax#33]
I'm interested in converting Reactome BioPAX pathways into signed directed pairwise graphs. My goal is to have an output similar to the [binary relations](https://www.pathwaycommons.org/pc2/formats) in Pathway Commons but to retain interaction signs (activation, inhibition) when they exist in the original reaction.  Is PyBioPAX an appropriate tool for that?  Would something higher-level like INDRA be better?

**Comment by bgyori** [comment]
Hi @agitter, I apologize that I missed your message earlier. In the case of PathwayCommons (which includes Reactome), the conversion from BioPAX to binary SIF is done using pattern search implemented in a submodule of the Paxtools package (https://github.com/BioPAX/Paxtools/tree/master/pattern). These patterns recognize certain constructs at the reaction-level representation of BioPAX models and when a match is found, one or more binary relations are created. PyBioPAX doesn't currently implement the functionalities of this pattern search though it could be done in principle with additional work. In INDRA, I effectively implemented our own custom "pattern" searches to convert BioPAX reactions to INDRA Statements. This is a somewhat lossy process that is a good fit for the goals of INDRA but might not be a generally optimal solution, depending on your use case. If you're interested in trying INDRA for this task, you can do that by e.g., 
```python
from indra.sources import biopax
biopax_processor = biopax.process_owl('reactome.owl')
print(bp.statements)  # statements are in the statements attribute of the processor 
```

**Comment by agitter** [comment]
Thank you very much @bgyori for the helpful leads. I'll close this because the other resources you pointed me to look more relevant than PyBioPAX for this specific task.
