### ISSUE TITLE
Example/documentation for creating BioPax from scratch

### ISSUE THREAD

**Issue by matthiaskoenig** [indralab/pybiopax#36]
Hi all,
we want to create BioPax documents using this library.
Unfortunately, most/all examples are for reading/parsing biopax documents with the library.

As I understood the code, I have to collect objects and then create the BioPaxModel with it.
But I cannot get this to work. We want to create the repressilator from scratch as a demo if the library.

Here what we tried so far
```python
import pybiopax
from combine_notebooks import RESOURCES_DIR

from pybiopax.biopax.model import BioPaxModel
from pybiopax.biopax.base import Protein, Rna
from pybiopax.api import model_to_owl_str, model_from_owl_file

objects = {}
'''
<bp:Protein rdf:about="PX">
 <bp:xref rdf:resource="http://identifiers.org/uniprot/P03023" />
 <bp:displayName rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">LacI protein</bp:displayName>
</bp:Protein>
'''
p = Protein(uid="PX", display_name="LacI protein", standard_name=None, cellular_location=None)
objects["PX"] = p

model = BioPaxModel(objects=objects, xml_base="http://www.biopax.org/release/biopax-level3.owl#")
owl_str: str = model_to_owl_str(model)

print("-" * 80)
print(owl_str)
print("-" * 80)
```
But results in 
```python
Traceback (most recent call last):
  File "/home/mkoenig/git/combine-notebooks/src/combine_notebooks/example_biopax.py", line 53, in <module>
    model = BioPaxModel(objects=objects, xml_base="http://www.biopax.org/release/biopax-level3.owl#")
  File "/home/mkoenig/.virtualenvs/combine_notebooks/lib/python3.9/site-packages/pybiopax/biopax/model.py", line 33, in __init__
    self.add_reverse_links()
  File "/home/mkoenig/.virtualenvs/combine_notebooks/lib/python3.9/site-packages/pybiopax/biopax/model.py", line 94, in add_reverse_links
    val = getattr(obj, attr)
  File "/home/mkoenig/.virtualenvs/combine_notebooks/lib/python3.9/site-packages/pybiopax/biopax/base.py", line 136, in name
    return std_name + disp_name + self._name
TypeError: can only concatenate list (not "NoneType") to list
```
I assume there are certain things which have to be done (i.e. object attributes to be set and order of objects to be added) for the model to be valid and be creatable with the library.

An example of how to create a simple biopax document would help a lot (RNA; Protein, Translation, BiochemicalReaction, Degradation).

Best Matthias

**edit: fixed code example

**Comment by bgyori** [comment]
Hi @matthiaskoenig , thanks for this, I agree we should add an example of BioPAX construction! It looks to me like the main problem with the above is that all name fields (in fact most attributes in BioPAX) are list-like so one has to use `[]` instead of `None` for missing values and pass in a list instead of a single string for existing values. I will try to post more specifics later today.

**Comment by bgyori** [comment]
My comment above was relevant though not precise since display name and standard name aren't actually list like per the BioPAX specification. I made some changes in #37 that make "manual" construction of BioPAX objects easier by allowing omission of parameters in constructors that aren't explicitly needed. With the above, your example boils down to:

```
import pybiopax

from pybiopax.biopax.model import BioPaxModel
from pybiopax.biopax.base import Protein
from pybiopax.api import model_to_owl_str

objects = []
p = Protein(uid="PX", display_name="LacI protein")
objects.append(p)

model = BioPaxModel(objects={o.uid: o for o in objects},
                    xml_base="http://www.biopax.org/release/biopax-level3.owl#")
owl_str: str = model_to_owl_str(model)

print("-" * 80)
print(owl_str)
print("-" * 80)
```
which prints

```
--------------------------------------------------------------------------------
<?xml version='1.0' encoding='utf-8'?>
<rdf:RDF xmlns:xsd="http://www.w3.org/2001/XMLSchema#" xmlns:owl="http://www.w3.org/2002/07/owl#" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:bp="http://www.biopax.org/release/biopax-level3.owl#" xml:base="http://www.biopax.org/release/biopax-level3.owl#">
  <owl:Ontology rdf:about="">
 <owl:imports rdf:resource="http://www.biopax.org/release/biopax-level3.owl#"/>
  </owl:Ontology>

<bp:Protein rdf:ID="PX">
 <bp:displayName rdf:datatype="http://www.w3.org/2001/XMLSchema#string">LacI protein</bp:displayName>
</bp:Protein>
</rdf:RDF>

--------------------------------------------------------------------------------
```

I will look into putting together a more comprehensive example of model construction but it might take a bit of time.

**Comment by matthiaskoenig** [comment]
Thanks this is great. And gets us started.

The main issue on our side is to figure out which parameters to provide in the constructors, because all the kwargs are directed to parent (and grandparent, ... ) classes in combination with composition. So in the end I have no clue what can/must be provided.

**Comment by bgyori** [comment]
I understand what you mean. I can suggest two things that might immediately help with figuring out exactly which BioPAX class has which attributes:
- The BioPAX Level 3 specification: http://www.biopax.org/release/biopax-level3-documentation.pdf
- The BioPAX OWL docs: http://www.biopax.org/owldoc/Level3/

Unfortunately, I don't think any of these will tell you all the attributes child classes inherit from their parent classes. I've looked into it a bit before but haven't yet figured out how to achieve this with the automated documentation generation but agree it would be useful.

**Comment by matthiaskoenig** [comment]
Thanks so much. This is great.
