### ISSUE TITLE
Pass tqdm kwargs

### ISSUE THREAD

**Issue by eggplants** [indralab/pybiopax#44]
Progress bar `Processing OWL elements...` cannot customize for now. I would like to pass some tqdm options like `disable` and custom `desc` to tqdm.

**Comment by bgyori** [comment]
Thanks @eggplants, we did consider that but at some point I decided against it since it needs to be added to a large number of API functions and clutters the API with technical arguments. However, if this is an issue, we can revisit it and come up with some option to be able to modify the tqdm message.

**Comment by eggplants** [comment]
How about `fn(..., *, tqdm_options: dict[str, Any]|None={"desc":"foo bar"})`

**Comment by bgyori** [comment]
I don't love the idea of adding tqdm arguments to every top-level API function but if there is no nicer way to achieve this, we might do that.

**Comment by eggplants** [comment]
OK, instead of adding kw, I suggest to add a flag as module veriable like bool `DISABLE_TQDM` to `model.py` and refer it from `from_xml` / `to_xml`.

All I need is to be able to disable tqdm.

**Comment by bgyori** [comment]
Something like that sounds like a good compromise, I'll implement it.

**Comment by eggplants** [comment]
I know this feature is available with `pip install git+https://github.com/indralab/pybiopax@master`. But I'd appreciate if you create new release.

Changelog: 3b953fee1c5a15fcee2d8c12d654135062cc412e...7e3b3b2e9ee0d6c962b6705060addbb660f51545

**Comment by bgyori** [comment]
I made a new release on PyPI. Thanks for the good suggestions!
