### ISSUE TITLE
regionType for SequenceLocation but not NucleicAcidRegionReference

### ISSUE THREAD

**Issue by quirinmanz** [indralab/pybiopax#47]
Hi! 
Firstly, thank you for the useful tool!

I was wondering why `SequenceLocation` has a property `region_type`, while `NucleicAcidRegionReference` does not. From the Specification, it looks like this might be wrongly assigned. https://www.biopax.org/owldoc/Level3/objectproperties/regionType___-138062345.html
Am I mixing something up here?

Best,
Quirin

**Comment by bgyori** [comment]
Thanks @quirinmanz, I will look into this and let you know in a couple of hours.

**Comment by bgyori** [comment]
@quirinmanz I implemented this in #48. I don't think there is any particular reason, it was just an oversight. I suspect the reason I missed this initially is that it is never used in PathwayCommons content.
