### ISSUE TITLE
Interactions with multiple participants

### ISSUE THREAD

**Issue by annaritz** [indralab/pybiopax#9]
Hello - this parser is exactly what I'm looking for, thanks for developing and releasing it.  However, I think that some BioPAX L3 specifications are not complete.  For example, Interactions usually have multiple participants.  Here's an example of one such MolecularInteraction from PathwayCommons:

```
<bp:MolecularInteraction rdf:ID="MolecularInteraction_3ced45a9353861f30bd80b1363e2f2ec">
 <bp:xref rdf:resource="http://identifiers.org/pubmed/15677474" />
 <bp:evidence rdf:resource="#Evidence_667df2b67d18cc7ff8045bdb0aa6bf06" />
 <bp:comment rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">REPLACED http://pathwaycommons.org/pc11/MolecularInteraction_3ced45a9353861f30bd80b1363e2f2ec</bp:comment>
 <bp:dataSource rdf:resource="#Provenance_ea923e36420c1e3bfc803815579bc6d8" />
 <bp:participant rdf:resource="#Protein_1c43aa04092c501e606fe9fc01f65396" />
 <bp:participant rdf:resource="#Protein_81c2eafe0d50c9acd61c610449811693" />
</bp:MolecularInteraction>
```

From your code base, it seems like you only store one participant per interaction.  Is this information stored elsewhere in the model?

**Comment by bgyori** [comment]
HI @annaritz, thanks! I think you're right, the `participant` attribute of `Interaction`-s should be list-like. The reason I didn't notice this is probably because there aren't any `MolecularInteraction`-s in the test set. I can fix this and make a new release.

**Comment by bgyori** [comment]
Alright, I fixed this and released version 0.0.6. Let me know if this solved your issue and if you run into anything else!

**Comment by annaritz** [comment]
Thanks for fixing that quickly!  That fixed that issue, but I'm now having issues with PublicationXRef, which has id and db.

```
<bp:PublicationXref rdf:about="http://identifiers.org/pubmed/15677474">
 <bp:id rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">15677474</bp:id>
 <bp:db rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">pubmed</bp:db>
</bp:PublicationXref>
```

This and the previous tag was from PathwayCommons (NetPath Database).  Do you have documentation about what you are supporting from the BioPax Level3 documentation?  I suspect that NetPath uses older tags since it's an older database.

**Comment by bgyori** [comment]
I tried processing https://www.pathwaycommons.org/archives/PC2/v12/PathwayCommons12.netpath.BIOPAX.owl.gz, and everything worked for me, I get an object for that PublicationXref that looks correct:
```python
In [1]: from pybiopax import *

In [2]: model = model_from_owl_file('PathwayCommons12.netpath.BIOPAX.owl')
Processing OWL elements: 100%|██████████████████████████████████| 42620/42620 [00:03<00:00, 11112.30it/s]

In [3]: model.objects['http://identifiers.org/pubmed/15677474']
Out[3]: <pybiopax.biopax.util.PublicationXref at 0x11497a970>

In [4]: model.objects['http://identifiers.org/pubmed/15677474'].id
Out[4]: '15677474'

In [5]: model.objects['http://identifiers.org/pubmed/15677474'].db
Out[5]: 'pubmed'
```
What was the issue that you found?

**Comment by annaritz** [comment]
There was an error on my end -- yep, that works as expected. Thanks!
